### PR TITLE
WIP: NOOBS support

### PR DESCRIPTION
**Pull request by AaronDewes**
This is the first draft of NOOBS support. Even if the Raspberry Pi Foundation probably won't include this, it could be added to https://github.com/procount/pinn, a fork of NOOBS (OS list at https://github.com/procount/pinn-os). I created some images, replace them if you don't like them

### CODE REVIEW

**Comment by mayankchhabra** [comment]
Thanks for this, @AaronDewes. I've not used NOOBS personally, but from what I see online it's like an OS installer image for Raspberry Pi? 

Can you please share more details on what exactly does it achieve?

**Comment by AaronDewes** [comment]
Yes, It is an OS installer which can install multiple OSes on one SD card. It contains a list of OSes suitable for the RPi running from it, which it gets from the RPi Foundation (NOOBS) or procounts repos (PINN)

**Comment by AaronDewes** [comment]
As this PR itself doesn't work yet, please check `export-noobs/00-release/files/marketing/slides_vga/A.png` and `export-noobs/00-release/files/marketing/slides_vga/B.png`. These are images displayed during install telling more about the OS you can add more or remove/replace my images, they are just examples. The first one is based on your website, the second one on the README of this repo.

**Comment by AaronDewes** [comment]
Closing this PR, as this is incompatible with PINN (because PINN also can use external USB drives which makes umbrel incompatible with PINN) and umbrel is not likely to be added to NOOBS.

**Pull request closed without merging**
