### PR TITLE
Add QT for GUI version of umbrel-details

### PR DESCRIPTION
**Pull request by AaronDewes**
Only merge this if you want to have that GUI version in Umbrel. When this PR is merged, the new GUI can be added by a PR in Umbrel.
Source code of the GUI: https://github.com/AaronDewes/umbrel-details-gui

It would look like this: (example.com is the tor URL, screenshot wasn't created on Umbrel OS, so I put example.com in the file for the tor address)
example

### CODE REVIEW

**Comment by AaronDewes** [comment]
If you want to test with a different font or color, you can now modify this file: https://github.com/AaronDewes/umbrel-details-gui/blob/master/config.h (I don't know how much you know about C++, but it is easy to modify this file even without C++ knowledge)

**Comment by lukechilds** [comment]
@AaronDewes this honestly so cool but I'm not sure it's something we'd merge into the core of Umbrel OS.

Most users won't have Umbrel plugged into a screen, that's also not something we want to encourage. Ideally the Umbrel device should be somewhere safe out of view like a locked cabinet or basement. We don't want to encourage people to have Umbrel in their living room connected to their TV.

It's also useful to have the logs printing to the screen for debugging and quick access to a shell in emergencies.

But I really love what you've done here. https://github.com/AaronDewes/umbrel-details-gui is certainly a cool project that more advanced Umbrel users can manually install on their own the device if they choose to.

@mayankchhabra thoughts?

**Comment by AaronDewes** [comment]
I could also do something similar with a minimal version of a web browser I'm currently maintaining, https://github.com/EndorphinBrowser/browser, and make it display the dashboard directly, so it is possible to connect a screen and access the dashboard from there, and maybe add a feature to allow people to connect o a WiFi network from the Dashboard.

It would also be possible to add WiFi settings directly to the current version of https://github.com/AaronDewes/umbrel-details-gui.

About debug info: I could modify it to exit when clicked 10 times, which would make the terminal visible again, the logs are still there, and shell access also.

**Comment by mayankchhabra** [comment]
Yeah, this is absolutely very very cool indeed, @AaronDewes! Great job.

I agree with @lukechilds. We don't want to encourage the use of Umbrel as something like a PC (i.e. connected to a display). It's supposed to be a terminal device that's only accessible remotely via a web browser.

That being said, what you described @AaronDewes is definitely a cool idea and some users might find value in it. I'd also recommend shipping it as a separate project that advanced users could manually install if they want to, like Luke pointed out.

**Comment by phenomeus** [comment]
is this also possible to get on an directly attached display hat to the pi4? I got that screen already running from the raspiblitz project.

**Comment by AaronDewes** [comment]
It currently only shows a QR code, but it can be installed with this:
```
sudo apt install libqt5gui5 libqt5svg5 libqt5network5 -y
wget https://github.com/AaronDewes/umbrel-details-gui/releases/download/v0.2.2/umbrel-details-aarch64
./umbrel-details-aarch64 -platform eglfs
```

Please tell me if it works.

**Comment by phenomeus** [comment]
./umbrel-details-aarch64: 1: ./umbrel-details-aarch64: Syntax error: "(" unexpected 

uname -a
Linux raspberrypi 5.4.51-v7l+ #1333 SMP Mon Aug 10 16:51:40 BST 2020 armv7l GNU/Linux

**Comment by AaronDewes** [comment]
Probably.

**Comment by phenomeus** [comment]
@AaronDewes build it from source finally on my pi4 32bit: getting this error 
export QT_QPA_EGLFS_HIDECURSOR=1
./umbrel-details -platform eglfs

> Could not find DRM device!
Aborted

lcd driver for display hat are missing, maybe that's the reason?

**Comment by AaronDewes** [comment]
Yes, it's probably a driver issue, I only tested on an HDMI screen, not anywhere else.

**Pull request closed without merging**
