### PR TITLE
Replace bsdtar with libarchive-tools

### PR DESCRIPTION
**Pull request by AaronDewes**

### CODE REVIEW

**Comment by lukechilds** [comment]
Just quickly tested on my existing Umbrel OS install and it doesn't look like we have `bsdtar` installed, only GNU `tar`:

```
umbrel@umbrel:~ $ tar --version
tar (GNU tar) 1.30
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
umbrel@umbrel:~ $ bsdtar --version
-bash: bsdtar: command not found
```

Is that expected? Do we need `bsdtar` if we have GNU `tar`? Should that binary be available in existing Umbrel OS installs?

**Comment by AaronDewes** [comment]
1. Bsdtar is needed on the build host, not on the target.
2. It is only used if NOOBS images are created, so if we delete the export-noobs folder (The scripts aren't run anyway in the current Umbrel), the dependency could be removed anyway.

**Comment by lukechilds** [comment]
Ah, of course! I was thinking this was running on the device, not the host.

Thanks @AaronDewes!

**Review by lukechilds — APPROVED** [review]

**Comment by lukechilds** [comment]
For future reference, see here for reasoning: https://github.com/getumbrel/umbrel-os/pull/112#issuecomment-691474333

**Pull request merged**
