### PR TITLE
Change image name from umbr3l-lite.zip to umbrel-<tag>.zip

### PR DESCRIPTION
**Pull request by lukechilds**
I think this name is a bit neater.

So on a release tag the zip will be called:

```
umbrel-v1.2.3.zip
```

On a normal commit it will be:

```
umbrel-v0.0.4-beta.3-1-g4893c29.zip
```

Which is:

```
umbrel-<most recent tag>-<no of commits since most recent tag>-g<commit hash prefix>.zip
```

**Note:** I haven't tested this yet, I'll let it run live on GitHub actions to check.

### CODE REVIEW

**Comment by mayankchhabra** [comment]
Awesome, thanks. Very clean, I can't tell how for how long this has bothered me too. 😂

**Comment by lukechilds** [comment]
Can I enable GitHub Actions builds on PRs?

**Comment by mayankchhabra** [comment]
Yeah, we can (should) do that. It's free, why not haha.

**Comment by lukechilds** [comment]
Also `umbrel-v1.2.3.zip` or `umbrel-os-v1.2.3.zip`?

**Comment by mayankchhabra** [comment]
`umbrel-os-v1.2.3.zip` 👍

Because `umbrel-v1.2.3.zip` can be confused with `getumbrel/umbrel`

**Comment by mayankchhabra** [comment]
Can you also _prettify_ the default SSH password from `umbr3lb0x` to something else while you're at it? Trying to think of something funny

**Comment by lukechilds** [comment]
>Because umbrel-v1.2.3.zip can be confused with getumbrel/umbrel

My thoughts exactly.

>Can you also prettify the default SSH password from umbr3lb0x to something else while you're at it? Trying to think of something funny

Yeah, I'll do it in a new PR.

**Comment by lukechilds** [comment]
All appears to be working, I can't test `.github/workflows/on-tag-only.yml` until we actually tag a new release but I think it should work ok.

If it fails for any reason we can just manually upload the release asset and then fix the issue.

**Comment by mayankchhabra** [comment]
Sounds good, nothing in life thrills as much as testing on `master`. ;)

**Pull request merged**
